apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce-ui
        version: v1
    spec:
      containers:
      - name: ecommerce-ui
        image: rslim087/ecommerce-ui:latest
        ports:
        - containerPort: 4000
        env:
        - name: REACT_APP_PROFILE_API_HOST
          value: "http://profile-management"
        - name: REACT_APP_PRODUCT_API_HOST
          value: "http://product-catalog"
        - name: REACT_APP_INVENTORY_API_HOST
          value: "http://product-inventory"
        - name: REACT_APP_ORDER_API_HOST
          value: "http://order-management"
        - name: REACT_APP_SHIPPING_API_HOST
          value: "http://shipping-and-handling"
        - name: REACT_APP_CONTACT_API_HOST
          value: "http://contact-support-team"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: ecommerce-ui
