apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-management
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
      version: v1
  template:
    metadata:
      labels:
        app: profile-management
        version: v1
    spec:
      containers:
      - name: profile-management
        image: rslim087/profile-management:1.0.0
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: profile-management
  namespace: ecommerce
spec:
  ports:
  - port: 3003
    name: http
  selector:
    app: profile-management
